# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stt_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x03stt\"\x1e\n\rSpeechRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"e\n\x0eSpeechResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btranslation\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2L\n\nSTTService\x12>\n\x13\x43onvertSpeechToText\x12\x12.stt.SpeechRequest\x1a\x13.stt.SpeechResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHREQUEST']._serialized_start=26
  _globals['_SPEECHREQUEST']._serialized_end=56
  _globals['_SPEECHRESPONSE']._serialized_start=58
  _globals['_SPEECHRESPONSE']._serialized_end=159
  _globals['_STTSERVICE']._serialized_start=161
  _globals['_STTSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
