# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\"\x1e\n\x0e\x43onvertRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0f\x43onvertResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32:\n\nTTSService\x12,\n\x07\x43onvert\x12\x0f.ConvertRequest\x1a\x10.ConvertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=13
  _globals['_CONVERTREQUEST']._serialized_end=43
  _globals['_CONVERTRESPONSE']._serialized_start=45
  _globals['_CONVERTRESPONSE']._serialized_end=77
  _globals['_TTSSERVICE']._serialized_start=79
  _globals['_TTSSERVICE']._serialized_end=137
# @@protoc_insertion_point(module_scope)
