# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bot_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/bot_service.proto\x12\x0b\x62ot_service\"G\n\x13GenerateTextRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_history\x18\x02 \x01(\t\"L\n\x14GenerateTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_history\x18\x02 \x01(\t2c\n\x0cModelService\x12S\n\x0cGenerateText\x12 .bot_service.GenerateTextRequest\x1a!.bot_service.GenerateTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.bot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATETEXTREQUEST']._serialized_start=41
  _globals['_GENERATETEXTREQUEST']._serialized_end=112
  _globals['_GENERATETEXTRESPONSE']._serialized_start=114
  _globals['_GENERATETEXTRESPONSE']._serialized_end=190
  _globals['_MODELSERVICE']._serialized_start=192
  _globals['_MODELSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
