# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63oordinator_service.proto\x12\x0b\x63oordinator\"\"\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\x9a\x01\n\x0b\x43oordinator\x12\x44\n\x0cProcessAudio\x12\x19.coordinator.AudioRequest\x1a\x19.coordinator.TextResponse\x12\x45\n\x0eGetBotResponse\x12\x18.coordinator.TextRequest\x1a\x19.coordinator.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=42
  _globals['_AUDIOREQUEST']._serialized_end=76
  _globals['_TEXTREQUEST']._serialized_start=78
  _globals['_TEXTREQUEST']._serialized_end=105
  _globals['_TEXTRESPONSE']._serialized_start=107
  _globals['_TEXTRESPONSE']._serialized_end=135
  _globals['_COORDINATOR']._serialized_start=138
  _globals['_COORDINATOR']._serialized_end=292
# @@protoc_insertion_point(module_scope)
