# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)


_sym_db = _symbol_database.Default()








DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\"G\n\x13GenerateTextRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_history\x18\x02 \x01(\t\"e\n\x14GenerateTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_history\x18\x02 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\x01\x32K\n\x0cModelService\x12;\n\x0cGenerateText\x12\x14.GenerateTextRequest\x1a\x15.GenerateTextResponseb\x06proto3')


_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
 DESCRIPTOR._loaded_options = None
 _globals['_GENERATETEXTREQUEST']._serialized_start=23
 _globals['_GENERATETEXTREQUEST']._serialized_end=94
 _globals['_GENERATETEXTRESPONSE']._serialized_start=96
 _globals['_GENERATETEXTRESPONSE']._serialized_end=197
 _globals['_MODELSERVICE']._serialized_start=199
 _globals['_MODELSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)


